# 项目相关配置
zyy:
  # 名称
  name: zyycms
  # 版本
  version: 3.8.5
  # 版权年份
  copyrightYear: 2023
  # 实例演示开关
  demoEnabled: false
  # 本地项目路径
  projectPath: D:/zyycmskyb
  # 文件上传路径 示例（ Windows配置 D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: ${zyy.projectPath}/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math
  # 静态化配置
  staticHtml: ${zyy.projectPath}/html
  # 索引存放位置
  lucenePath: ${zyy.projectPath}/lucene

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8083
  max-http-header-size: 2MB
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100
    max-http-form-post-size: -1

# 日志配置
logging:
  level:
    com.zyy: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
#    prefix: classpath:/templates/
    suffix: .html
    # 禁用缓存
    cache: false
    prefix: file:///${zyy.projectPath}/template/
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: server
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  300MB
       # 设置总上传的文件大小
       max-request-size:  500MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  resources:
    static-locations: file:///${zyy.projectPath}/template/,file:///${zyy.projectPath}/html/
  mvc:
    static-path-pattern: /**
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

  mail:
    protocol: smtps
    # 配置 SMTP 服务器地址 smtp.qq.com
    host: smtp.ym.163.com
    # 发送者邮箱，已开通POP3/SMTP服务的邮箱，也就是你自己的
    username: sunshuaipeng@hnzyy.ltd
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码 wqkqidzjtmiadjfc PKOHRFNVQYFMJSKI
    password: sun2448200847
    # 发送人昵称
    nickname: hnzyy sun
    # 端口号465或587（QQ邮箱发送邮件仅支持587端口协议）
    port: 994
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 接收者邮箱
    receive: 2448200847@qq.com
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: false


# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌密钥
    secret: hnzyy2023
    # 令牌有效期（默认30分钟）
    expireTime: 30

# MyBatis配置
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.zyy.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: false
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

